feat(contact-form): complete logic and designs
CollActionteam/collaction_app pull request #75
Opened 2021-12-05 06:26 UTC by yasht01

- Updated designs to the latest Figma file.
- Add `client.post()` call for sending contact form data.
- Update tests to work with latest designs.

2021-12-05 18:47 UTC, wizlif requested changes

2021-12-05 18:47 UTC, wizlif commented on lib/infrastructure/contact_form/contact_form_api.dart
> +import 'package:collaction_app/domain/user/user.dart';
Use relative imports

2021-12-05 18:47 UTC, wizlif commented on lib/infrastructure/contact_form/contact_form_api.dart
> +  // final _authRepository = getIt<IAuthRepository>();
Remove unused import

2021-12-05 18:47 UTC, wizlif commented on lib/infrastructure/contact_form/contact_form_api.dart
> +    // final token = await userData.fold(() => null, (a) async => a.getIdToken());
Remove unused imports

2021-12-05 18:47 UTC, wizlif commented on lib/presentation/contact_form/contact_form_screen.dart
> +import 'package:collaction_app/presentation/shared_widgets/pill_button.dart';
Use relative imports

2021-12-05 19:50 UTC, Xazin commented on lib/infrastructure/contact_form/contact_form_api.dart
> +    final bodyJson =
Let's make a DTO model for this using Freezed.

2021-12-05 19:50 UTC, Xazin commented on lib/infrastructure/contact_form/contact_form_api.dart
> +          body: bodyJson,
Use the `toJson` from the ContactFormDto class once you've created it.

2021-12-05 19:51 UTC, Xazin commented on lib/presentation/contact_form/contact_form_screen.dart
> +                              "We will send out response to your email address",
`out` => `our`

2021-12-08 09:33 UTC, Xazin commented
@wizlif @yasht01 
Please review again, check the commit I pushed on top.

2021-12-08 09:42 UTC, Xazin commented
Closed due to #78

2021-12-08 09:42 UTC, closed without merging